### ISSUE TITLE
.include throws error on find query when result is empty

### ISSUE THREAD

**Issue by sh** [snd/mesa#17]
````sql
CREATE TABLE "user" (
  id SERIAL PRIMARY KEY,
  name text NOT NULL
);
CREATE TABLE "address" (
  id SERIAL PRIMARY KEY,
  user_id integer NOT NULL REFERENCES "user"(id),
  city text NOT NULL
);
````

````js
userTable = database.table('user');
addressTable = database.table('address');

userTable
  .include({first: true}, addressTable)
  .find(function(users) {

  })
````

````
Unhandled rejection Error: `in` with empty array as right operand
  at Object.dsl.(anonymous function).modifiers.(anonymous function) [as in] (/app/node_modules/fragments-postgres/node_modules/mesa/node_modules/mohair/node_modules/criterion/src/criterion.js:423:17)
  at criterion (/app/node_modules/fragments-postgres/node_modules/mesa/node_modules/mohair/node_modules/criterion/src/criterion.js:603:21)
  at Object.Mohair.where (/app/node_modules/fragments-postgres/node_modules/mesa/node_modules/mohair/lib/mohair.js:565:23)
  at Object.Mesa.where (/app/node_modules/fragments-postgres/node_modules/mesa/lib/mesa.js:216:63)
  at /app/node_modules/fragments-postgres/node_modules/mesa/lib/mesa.js:605:30
From previous event:
  at reducer (/app/node_modules/fragments-postgres/node_modules/mesa/lib/mesa.js:601:20)
  at Array.reduce (native)
  at Object.Mesa.baseEmbed (/app/node_modules/fragments-postgres/node_modules/mesa/lib/mesa.js:635:21)
  at Object.Mesa.embed (/app/node_modules/fragments-postgres/node_modules/mesa/lib/mesa.js:642:17)
  at Object.bound (/app/node_modules/fragments-postgres/node_modules/mesa/node_modules/lodash/dist/lodash.js:957:21)
From previous event:
  at reducer (/app/node_modules/fragments-postgres/node_modules/mesa/lib/mesa.js:458:20)
  at Array.reduce (native)
  at Object.Mesa.runQueue (/app/node_modules/fragments-postgres/node_modules/mesa/lib/mesa.js:460:18)
  at Object.Mesa.afterQuery (/app/node_modules/fragments-postgres/node_modules/mesa/lib/mesa.js:475:17)
  at /app/node_modules/fragments-postgres/node_modules/mesa/lib/mesa.js:568:19
From previous event:
  at Object.Mesa.find (/app/node_modules/fragments-postgres/node_modules/mesa/lib/mesa.js:567:29)
  ....
  at processImmediate [as _immediateCallback] (timers.js:367:17)
````

**Comment by snd** [comment]
fixed in mesa 1.0.0-alpha.12 and fragments-postgres 1.0.0-beta.10
